name: Docker Auto Test
on: [push] 

jobs:
  run-docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Run Docker Test
        run: |
          docker build -t my-test-app .
          docker run my-test-app
